### ISSUE TITLE
Which query image you choose for each seqs ?

### ISSUE THREAD

**Issue by fangdaoyou** [Spritea/GMOT40#5]
hello, I would like follow your great work, but I can't find any information about query image, which query image you choose for each seqs ?

**Comment by Spritea** [comment]
Hi, if you do this task by using the public detection result provided (public detector), you don't need the template information. If you use your own detection method (private detector), you could check the zip file here for the template information. Note the box format is [top_left_x, top_left_y, width, height].

[template_box_by_seq_for_global_track.zip](https://github.com/Spritea/GMOT40/files/8863642/template_box_by_seq_for_global_track.zip)

**Comment by fangdaoyou** [comment]
> Hi, if you do this task by using the public detection result provided (public detector), you don't need the template information. If you use your own detection method (private detector), you could check the zip file here for the template information. Note the box format is [top_left_x, top_left_y, width, height].
> 
> [template_box_by_seq_for_global_track.zip](https://github.com/Spritea/GMOT40/files/8863642/template_box_by_seq_for_global_track.zip)

thank you for your reply！
