### ISSUE TITLE
GlobalTrack

### ISSUE THREAD

**Issue by yumu-173** [Spritea/GMOT40#7]
Hello, may I ask if it's possible to provide the training code for the improved GlobalTrack? We have tried the original GlobalTrack for GMOT-40 detection, but it seems that we cannot achieve the results described in the paper.

**Comment by Spritea** [comment]
Hi, we did not train GlobalTrack. We directly use their trained model to do inference on GMOT-40 dataset. We use the official implementation of GloablTrack without any architecture modifications. You may check the [GlobalTrack ](https://github.com/huanglianghua/GlobalTrack)repo for more infomation if your result looks wrong.
